language: node_js
node_js:
  - "8"
cache: yarn
addons:
  apt:
    packages:
      - g++-4.8
    sources:
      - ubuntu-toolchain-r-test
env:
  CXX=g++-4.8
branches:
  only:
    - master
before_script:
  # if you're have troubles with firebase/firebase-tools#382
  # - "yarn globar add https://github.com/firebase/firebase-tools"
  - npm install -g firebase-tools
  - npm install -g gatsby-cli
script:
  - npm test
  - npm build
after_success:
  - "firebase deploy --token=${FIREBASE_TOKEN}"