language: node_js
node_js: "lts/dubnium"
cache: npm
before_script:
  - npm install -g firebase-tools
  - npm install -g gatsby-cli
script:
  - npm run-script build
deploy:
  - provider: firebase
    token:
      secure: "XWdaWEL4nODbMSpNgLFlIZXSt2ycZ/94u59HkyRynKJFtOBym9QnDssgi9tDAI85nKv4pDw7DLQ3BLolM1kXUpSRchlhZz3gk5ymB93wTgI/d4VF2KTWO3euJEN7DIgMcFPZMyw1EZqNxc8Zyv/d4P5J+XNy1/r4xGdQAY23eAbjR+M33RhwFlOmP8mlHxYd8dVg1WIWxdrduuD2tvpIv7w+KG/6qtYevhdgy5xEtEguUORI8W6B9Y3jglofLTIGxPPTGpJ7JxLqBwdyGTj1lwigay3XquX0Dsxw0bQEpBZMeshDHhRg7IwuNoWaaNDFJSJYPZSIFRZH8A/vwtWUQF2T8+cv1xWzNugqnWJSUn3VUpiFi1EkLF0HY32yAfUxjTr5gMJLMN0P8gQ/Iw7O1qQEB5DCVntHAwwPAEhn5bjCJyC/Mwe8d+g/3hotQABvX6YYWTtoUkV4TMRtLUq/BBFuFhxvhR+dSgMSXlzavepb0XwHkQHIyGXuFuRf1hQBZIboUY8QaJ3itpX7/914XXQTkweZ7Kc2SHZdIZBsigVGUIWqpfXF2S3AGKPVXJvX4FQs5VuwYc9mYdo+TWE5UZ6P8x4AFHOCLP86QQoj3QJ03YdAgXAsrtuX6LMV9/yH93O6nl93GQ2eo3wC6sUT6BnzsJl3bdbWVDC2kGZ05tI="
    message: "Staging deploy from travis."
    project: tos-manizales
    skip_cleanup: true
    on:
      branch: master
      repo: coreofscience/tos.coreofscience.com
  - provider: firebase
    token:
      secure: "T9s3tvbIXDJ3aDth1Zt91JibuezdHCSNDL+6SK718mrfOomtQUK2kMNuh61u8/Q/pcfV2XpI8UukbD0azpXAXuhSUG1y+Dr0UrMjFSrbCdL0bET0hYFB+GlXKZPUc+3XZ6p+E3iEagYaNEzk5R50KVoBJ0qP3czJldFLWK4hi8WMMCnnvnFFcML50RnlGPMI5IHPthftORtHYXDDDAlOAUABy2dPL7WaO1kHGaMISnNjI5EAlLPQLyeTlLCbFG01wjQQCPX/ZqBuspSIq2Wh2BINiENuIGS6EcWN7oDM57T5oD9r8NalV9iNY/z/G1ueWnjBia3MV2qldyIL9SYnba694BAI3pPCJRRVhbzOF4pWy7Jn3Wa7eBHa354bf6o06ZC7M/0w+PPpZmwbfKBde08R0pg+LnEzeOTN1BTGCJKKG5e+K/dYrGEb4RXe5U/707ud5mX6+DudYomIa+WUMS0W/q3Kqg7h2nqmr56PGh1m/SvRVSTXJPqswFVLt61ayrk1Dpq3NIXFSiJ5nwjret2/IpW+sXP0Uzr8AFypWDiicMfjpFAOZJAF27ga3U3Bag7/85diyzPvgeH3K7bbMSNkrTDeNzin1r01p/qsConhvKLcflTrs/VtI4zMLdBF9gjoShI9k3izn7hH31Ct3uwbMhovQEquw55E85ZHmds="
    message: "Production deploy from travis."
    project: tos-coreofscience
    skip_cleanup: true
    on:
      tags: true
      branch: master
      repo: coreofscience/tos.coreofscience.com